#!/bin/bash

DEB_USER=stomp
set +e
# Creating a new user
ret=false
getent passwd $DEB_USER >/dev/null 2>&1 && ret=true
if [ ${ret} == false ];
then
        sudo su -c "useradd -r -s /bin/nologin $DEB_USER"
fi

